# Base image
FROM node:20.10.0-alpine as development

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json package-lock.json ./

# Install nestjs/cli globally
RUN npm install -g @nestjs/cli

# Install app dependencies only if NODE_ENV is not set to "development"
RUN npm install

# Bundle app source
COPY . .

# Start the server using the appropriate command based on the environment
CMD [ "npm", "run", "start:dev"]
