FROM node:20.10.0-alpine

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install

COPY . .

# Creates a "dist" folder with the production build
RUN npm run build

# Bundle app source
COPY . .

EXPOSE 3000
# Start the server using the production build
CMD [ "node", "dist/main" ]
