version: '3.9'

services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    # Consider removing the volume mount for production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
    depends_on:
      - nest
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl/certs:/etc/nginx/certs
    command: [nginx, '-g', 'daemon off;']

  postgres:
    container_name: postgres
    image: 'postgres:16'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ovioo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
