version: '3.9'

services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
    depends_on:
      - nest
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl/certs:/etc/nginx/certs
    command: [nginx, '-g', 'daemon off;']

volumes:
  postgres_data:
