version: '3.9'

services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
    depends_on:
      - nest
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl/certs:/etc/nginx/certs

volumes:
  postgres_data:

networks:
  default:
    name: ovioo_default
