name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy 
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 91.108.112.154
        username: root
        key: ${{ secrets.ubuntu }}
        script: |
          cd demo/live
          docker-compose -f docker-compose.prod.yml up -d --build
